In [66]:
import sys
import os
import scanpy as sc
# Parent directory of Nutkin
project_root = os.path.abspath("..")  # the parent directory of the test folder
sys.path.append(project_root)

import nutkin.preprocessing

In [24]:
data_path="...Nutkin/data/test_data.h5ad"
adata = sc.read_h5ad(data_path)
print(adata)

AnnData object with n_obs × n_vars = 1932 × 31053
    obs: 'barcode', 'bc.umi.count', 'num_barcodes', 'max_umi', 'lineage_barcodes_filtered', 'umi_counts_filtered', 'clone_id', 'louvain', 'clone_plot_group'
    var: 'gene_ids'
    uns: 'log1p', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

/home/jiayueqin/.local/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [25]:
output_path=".../Nutkin/test/result"

In [36]:
adata = nutkin.preprocessing.load_data(
        data_path=data_path,
        output_path=output_path,
        n_comps=50,
        run_pca=True,
        run_embedding=True,
        group_col='clone_id'
)

/home/jiayueqin/.local/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

Successfully loaded data from: /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/test_data.h5ad
Data detected as PREPROCESSED. Skipping core preprocessing steps.
Generating UMAP embedding...
WARNING: saving figure to file /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/Nutkin/test/result/umapumap_plot.png

In [56]:
from nutkin.nutkin import Nutkin

In [39]:
adata = sc.read(".../Nutkin/test/result/preprocessed_data.h5ad")

/home/jiayueqin/.local/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [57]:
nut = Nutkin(
        adata=adata,
        group_col='clone_id',
        output_path=output_path,
        detail=True
    )

In [59]:
nut.measure()

Quantifying variability using MAD method

Running dimensional reduction (PCA)...

Saving results

                   group  number of cells  sum statistics
0   mCHERRY_Barcode_1614              492        2.876896
1  mCHERRY_Barcode_65372              229        2.880755
2   mCHERRY_Barcode_1755              404        2.938006
3   mCHERRY_Barcode_5774              807        3.028224

In [53]:
nut.differential_test(group1=['mCHERRY_Barcode_1614','mCHERRY_Barcode_1614'],group2=['mCHERRY_Barcode_5774','mCHERRY_Barcode_1755'])

Conducting differential analysis using MAD method

['mCHERRY_Barcode_1614', 'mCHERRY_Barcode_1614']
['mCHERRY_Barcode_5774', 'mCHERRY_Barcode_1755']
Comparing mCHERRY_Barcode_1614 and mCHERRY_Barcode_5774

Running dimensional reduction (PCA)...

Running Bootstrapping

/data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/Nutkin/nutkin/nutkin.py:498: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out_df = pd.concat([out_df, pd.DataFrame([new_row_clean])], ignore_index=True)

Comparing mCHERRY_Barcode_1614 and mCHERRY_Barcode_1755

Running Bootstrapping

Saving results

,groupA,number of cells in groupA,sum statistics for groupA,groupB,number of cells in groupB,sum statistics for groupB,null hypothesis,test statistics sum,p value sum
0,mCHERRY_Barcode_1614,492,2.883417,mCHERRY_Barcode_5774,807,3.024845,A = B,-0.141428,0.059876
1,mCHERRY_Barcode_1614,492,2.883417,mCHERRY_Barcode_1755,404,2.951270,A = B,-0.067853,0.379960

In [60]:
nut.differential_test()

Conducting differential analysis using MAD method

Comparing mCHERRY_Barcode_1614 and mCHERRY_Barcode_65372

Running Bootstrapping

/data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/Nutkin/nutkin/nutkin.py:498: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out_df = pd.concat([out_df, pd.DataFrame([new_row_clean])], ignore_index=True)

Comparing mCHERRY_Barcode_65372 and mCHERRY_Barcode_1755

Running Bootstrapping

Comparing mCHERRY_Barcode_1755 and mCHERRY_Barcode_5774

Running Bootstrapping

Saving results

,groupA,number of cells in groupA,sum statistics for groupA,groupB,number of cells in groupB,sum statistics for groupB,null hypothesis,test statistics sum,p value sum
0,mCHERRY_Barcode_1614,492,2.876896,mCHERRY_Barcode_65372,229,2.880755,A = B,-0.003859,0.984375
1,mCHERRY_Barcode_65372,229,2.880755,mCHERRY_Barcode_1755,404,2.938006,A = B,-0.057251,0.381658
2,mCHERRY_Barcode_1755,404,2.938006,mCHERRY_Barcode_5774,807,3.028224,A = B,-0.090218,0.287236

In [61]:
nut.visualize_pca_results(detail=True, plot_type='both')

[('mCHERRY_Barcode_1614', 'mCHERRY_Barcode_65372'), ('mCHERRY_Barcode_65372', 'mCHERRY_Barcode_1755'), ('mCHERRY_Barcode_1755', 'mCHERRY_Barcode_5774')]
PCA visualization (both) saved to /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/Nutkin/test/result

In [68]:
import os
os.chdir(".../Nutkin/")

In [69]:
!python -m nutkin.main \
    --input_path .../Nutkin/data/test_data.h5ad \
    --output_path .../Nutkin/test/result/ \
    --group_col clone_id \
    --group1 mCHERRY_Barcode_1614 mCHERRY_Barcode_1614 \
    --group2 mCHERRY_Barcode_5774 mCHERRY_Barcode_1755 \
    --detail \
    --plot_type both

Welcome to


 N     N  U     U  TTTTTTTT  K     K  II  N     N
 N N   N  U     U     TT     K    K   II  N N   N
 N  N  N  U     U     TT     K  K     II  N  N  N
 N   N N  U     U     TT     KKK      II  N   N N
 N    NN  U     U     TT     K  K     II  N    NN
 N     N  U     U     TT     K    K   II  N     N
 N     N  UUUUUUU     TT     K     K  II  N     N



(28/01/2026 21:22:25) Loading and preprocessing data...
/home/jiayueqin/.local/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
Successfully loaded data from: /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/test_data.h5ad
Data detected as PREPROCESSED. Skipping core preprocessing steps.
Preprocessed data saved to: /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/test/result/preprocessed_data.h5ad
(28/01/2026 21:22:27) Initializing Nutkin...
(28/01/2026 21:22:28) Measuring variability...
Quantifying variability using MAD method

Running dimensional reduction (PCA)...

Saving results

(28/01/2026 21:22:29) Variability summary:
                   group  number of cells  sum statistics
0  mCHERRY_Barcode_65372              229        2.878739
1   mCHERRY_Barcode_1614              492        2.887869
2   mCHERRY_Barcode_1755              404        2.945253
3   mCHERRY_Barcode_5774              807        3.025150
(28/01/2026 21:22:29) Performing pairwise differential tests and plotting results...
Conducting differential analysis using MAD method

['mCHERRY_Barcode_1614', 'mCHERRY_Barcode_1614']
['mCHERRY_Barcode_5774', 'mCHERRY_Barcode_1755']
Comparing mCHERRY_Barcode_1614 and mCHERRY_Barcode_5774

Running Bootstrapping

/data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/Nutkin/nutkin/nutkin.py:498: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out_df = pd.concat([out_df, pd.DataFrame([new_row_clean])], ignore_index=True)
Comparing mCHERRY_Barcode_1614 and mCHERRY_Barcode_1755

Running Bootstrapping

Saving results

[('mCHERRY_Barcode_1614', 'mCHERRY_Barcode_5774'), ('mCHERRY_Barcode_1614', 'mCHERRY_Barcode_1755')]
PCA visualization (both) saved to /data/gpfs/projects/punim0614/jiayue/nutkin/real_data_analysis/test/result/